name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.2+7
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.20.1
  shared_preferences: ^2.3.5
  http: ^1.2.2
  connectivity_plus: ^6.1.2
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  country_code_picker: ^3.1.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.4
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.16
  shimmer_animation: ^2.2.2
  file_picker: ^8.1.5
  permission_handler: ^11.3.1
  syncfusion_flutter_datepicker: ^28.1.39
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_animarker: ^3.2.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^3.0.0
  flutter_widget_from_html_core: ^0.15.2
  flutter_typeahead: ^5.2.0
  dotted_line: ^3.2.3
  autocomplete_textfield: ^2.0.1
  flutter_inappwebview: ^6.1.5
  firebase_crashlytics: ^4.2.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  dart_pusher_channels: ^1.2.2+1
  flutter_switch: ^0.3.2
  just_the_tooltip: ^0.0.12
  speech_to_text: ^7.0.0
  app_links: ^6.3.3
  share_plus: ^10.1.4
  video_thumbnail: ^0.5.3
  video_player: ^2.9.2
  chewie: ^1.9.2
  firebase_auth: ^5.4.0
  phone_numbers_parser: ^9.0.3
  path: any
  flutter_inappwebview_ios: ^1.1.2



dependency_overrides:
   file_picker:
     git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/

  fonts:


    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Black.ttf
          weight: 600
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900


     
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa-Bold.ttf
